import 'styles/reset.scss';
import 'styles/variables.scss';
import 'styles/globals.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='app'>{children}</body>
    </html>
  )
}
